on:
  release:
    types: [published]
name: publish-npm-package
jobs:
  publish-npm-package:
    runs-on: ubuntu-latest
    steps:
      # The logic below handles the npm publication:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
      - run: |
          npm ci
          npm run prerelease
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
